language: go
go:
  - 1.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - llvm-3.7
      - clang-3.7
      - libclang1-3.7
      - libclang-3.7-dev

install:
  - mkdir -p /home/travis/bin
  - sudo ln -s /usr/bin/llvm-config-3.7 /home/travis/bin/llvm-config
  - sudo ldconfig

  - llvm-config --version
  - llvm-config --includedir
  - llvm-config --libdir

  - make install-dependencies
  - make install-tools

script:
  # Install the project
  - make install

  # Test without any coverage
  - make test-verbose

