language: go
go:
  - 1.7.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - llvm-3.7
      - clang-3.7
      - libclang1-3.7
      - libclang-3.7-dev

env:
  global:
    - CC=clang CXX=clang++

install:
  - mkdir -p /home/travis/bin
  - sudo ln -s /usr/bin/clang-3.7 /home/travis/bin/clang
  - sudo ln -s /usr/bin/llvm-config-3.7 /home/travis/bin/llvm-config
  - sudo ldconfig

  - llvm-config --version
  - llvm-config --includedir
  - llvm-config --libdir
  - clang --version

  - make install-dependencies
  - make install-tools

script:
  # Install the project
  - make install

  # Test without any coverage
  - make test-full
